{{- if .Values.global.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace.name }}
  labels:
    {{- include "lifi-bird-stack.labels" . | nindent 4 }}
{{- end }}
