apiVersion: v1
kind: Service
metadata:
  name: {{ include "get-bird-image.fullname" . }}
  namespace: {{ .Values.global.namespace.name }}
  labels:
    {{- include "get-bird-image.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "get-bird-image.selectorLabels" . | nindent 4 }}
